-- Migration: 00001_phase2a_schema
-- Description: Creates backend foundation tables for Phase 2A MVP

-- Drop tables if they exist (to ensure clean migration state during development)
-- DROP TABLE IF EXISTS admin_notes;
-- DROP TABLE IF EXISTS saved_courses;
-- DROP TABLE IF EXISTS saved_universities;
-- DROP TABLE IF EXISTS documents;
-- DROP TABLE IF EXISTS applications;
-- DROP TABLE IF EXISTS student_profiles;

CREATE TABLE student_profiles (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID UNIQUE, -- To be linked with auth.users later
  full_name TEXT NOT NULL,
  email TEXT NOT NULL,
  phone TEXT,
  preferred_countries TEXT[],
  degree_level TEXT,
  target_course TEXT,
  cgpa NUMERIC(4, 2),
  english_test TEXT,
  english_score NUMERIC(4, 1),
  gre_score INTEGER,
  gmat_score INTEGER,
  work_experience TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL
);

CREATE TABLE applications (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  student_id BIGINT REFERENCES student_profiles(id) ON DELETE CASCADE NOT NULL,
  university_name TEXT NOT NULL,
  course_name TEXT NOT NULL,
  status TEXT DEFAULT 'DRAFT' NOT NULL,
  notes TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL
);

CREATE TABLE documents (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  student_id BIGINT REFERENCES student_profiles(id) ON DELETE CASCADE NOT NULL,
  document_type TEXT NOT NULL,
  file_name TEXT NOT NULL,
  file_url TEXT,
  status TEXT DEFAULT 'UPLOADED' NOT NULL,
  uploaded_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL
);

CREATE TABLE saved_universities (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  student_id BIGINT REFERENCES student_profiles(id) ON DELETE CASCADE NOT NULL,
  university_name TEXT NOT NULL,
  country TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL,
  UNIQUE(student_id, university_name)
);

CREATE TABLE saved_courses (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  student_id BIGINT REFERENCES student_profiles(id) ON DELETE CASCADE NOT NULL,
  course_name TEXT NOT NULL,
  university_name TEXT NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL,
  UNIQUE(student_id, course_name, university_name)
);

CREATE TABLE admin_notes (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  student_id BIGINT REFERENCES student_profiles(id) ON DELETE CASCADE NOT NULL,
  admin_id UUID NOT NULL, -- To be linked with admin auth.users later
  note TEXT NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL
);

-- Triggers to automatically update the `updated_at` column
CREATE OR REPLACE FUNCTION update_modified_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ language 'plpgsql';

CREATE TRIGGER update_student_profiles_modtime
BEFORE UPDATE ON student_profiles
FOR EACH ROW EXECUTE PROCEDURE update_modified_column();

CREATE TRIGGER update_applications_modtime
BEFORE UPDATE ON applications
FOR EACH ROW EXECUTE PROCEDURE update_modified_column();

CREATE TRIGGER update_documents_modtime
BEFORE UPDATE ON documents
FOR EACH ROW EXECUTE PROCEDURE update_modified_column();
